sudo: false
language: java

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  fast_finish: true
  include:

    - stage: test
      name: "Linux"
      os: linux
    - name: Macos
      os: osx

    - stage: deploy
      name: "Deploy to Jetbrains marketplace"
      os: linux
