sudo: false
language: java

stages:
  - test
  - name: deploy
    # if: branch = master AND tag IS present

jobs:
  fast_finish: true
  include:

    - stage: test
      name: "Linux"
      os: linux
    - name: "Macos"
      os: osx

    - stage: deploy
      name: "Deploy to Jetbrains marketplace"
      os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then
      brew update;
      brew install openssl readline;
      brew outdated pyenv || brew upgrade pyenv;
    else
      pyenv update;
    fi
  - pyenv install 3.7.0
  - pyenv global 3.7.0
  - python --version

install:
  - pip install conan
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7;
    fi
